version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=3000
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_NAME=go-project
      - DB_URL=test:test@tcp(database:3306)/go-project?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - database
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: go-project
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./database:/var/lib/mysql
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database